### ISSUE TITLE
The package does not contain any script or entry points

### ISSUE THREAD

**Issue by dmerejkowsky** [Mithil467/mitype#11]
### Steps to reproduce

* Install `mitype` in a fresh virtualenv

### Expected behaviour

* A `mitype` script should be generated in `<venv-path>/bin`

### Actual behaviour
* Nothing is generated and you have to use `python -m mitype` to launch the app

### Your proposed fix 
* I can try and make a PR but if your goal is to learn more about package management you should try and fix this yourself :stuck_out_tongue: 

Nice app by the way :)

**Comment by Mithil467** [comment]
I'm very glad you brought up this issue and also proposed to help. I'll try to do it myself as you said, I need to learn :)

> Nice app by the way :)

Thank you! @dmerejkowsky
