### ISSUE TITLE
Storing project metadata in pyproject.toml

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#114]
Transition to [PEP 621](https://www.python.org/dev/peps/pep-0621/) by adding a pyproject.toml file and moving metadata from setup.py. This might be a good first issue for someone who has already worked with Python packaging rather than a complete novice.

**Comment by Dark-Knight11** [comment]
I would like to work on this issue

**Comment by Mithil467** [comment]
Thanks for your interest in contributing to mitype! @Dark-Knight11
