### ISSUE TITLE
Test records not saved in history

### ISSUE THREAD

**Issue by Dark-Knight11** [Mithil467/mitype#118]
### Subject of the issue
All test records are not being saved into history. If you give one test for a specific text sample and after finishing it you press `TAB` to retry again then the new retried test won't be saved into history only the first attempt is being saved.
Similarly, if you change the text with left and right arrow keys then that new test with new text is also not being saved.
Only the first test after running the tool is being saved.

### Your environment
* operating-system `Windows`
* version of Mitype `Mitype version 0.2.3+20.g052df91`
* version of Python `3.8.5`
* which terminal and it's version if applicable `Powershell 5.1.19041.1237`

### Steps to reproduce
1. Run mitype and give the test.
2. Press `TAB` to retry or change the text with left and right arrow keys.
3. Retry the same sample or attempt the new test with selected new text.
4. Exit mitype with `ESC`
5. Check history `mitype -H`
6. Check that only first test was saved into history, test at 3rd point isn't saved.

### Expected behaviour
All test records should be saved

### Actual behaviour
Only the first attempted test after running the tool is being saved

### Your proposed fix (if any)
Not sure what's the problem but I believe it lies in this code somewhere
https://github.com/Mithil467/mitype/blob/052df91c8b309819ef8702d26c4fe679cfb16a01/mitype/app.py#L288-L347

**Comment by Mithil467** [comment]
Thanks for the issue! @Dark-Knight11
