### ISSUE TITLE
Accuracy above 100

### ISSUE THREAD

**Issue by Dark-Knight11** [Mithil467/mitype#119]
### Subject of the issue
For a particular test, I got an accuracy of `102.42%`. 
Test sample ID: `1758`

### Your environment
* operating-system `Windows`
* version of Mitype `Mitype version 0.2.3+20.g052df91`
* version of Python `3.8.5`
* which terminal and it's version if applicable `Powershell 5.1.19041.1237`

### Steps to reproduce
Not sure how to reproduce right now. I got it by accident. I will add instructions once I figure it out.
I gave a test for ID `1758` and retired it few times and in one of the scores, accuracy was `102.42%`. 
I noticed it while I played its replay.

### Expected behaviour
Accuracy should not exceed `100%`

### Actual behaviour
Accuracy displayed was `102.42%`

**Comment by Mithil467** [comment]
Thanks for the issue @Dark-Knight11.
This is indeed weird, and hard to reproduce. 🤔

**Comment by Mithil467** [comment]
@Dark-Knight11 Thanks for the analysis. 🙌
The issue in your last commit has been fixed with #127.

**Comment by Mithil467** [comment]
Closing as non-reproducible. Might have been fixed with later changes. Please feel to re-open if issue persists.
