### ISSUE TITLE
Running `tox -e 2.7` on mitype gives error

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#14]
### Subject of the issue
Following the contributors guide, running `tox -e 2.7` on mitype gives error.
```
line 5, in <module>
        with open("README.md", encoding="utf-8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
```

### Expected behaviour
Should work fine.

### Actual behaviour
Command errors out with exit status 1

### Your proposed fix (if any)
We gotta modify that line under setup.py. But please be careful, because this file decides how mitype appears on [pypi](https://pypi.org/project/mitype/).

**Comment by andylim0221** [comment]
I'd like to take on this issue. Will submit PR during Hacktoberfest.

**Comment by Mithil467** [comment]
Hey @andylim0221 👋
Thanks for your interest!
Start from latest master, there might be some discrepancy between main repo and your fork as the git history was modified.
To be on a safer side, I would request you to refork this repo.

Please make sure you read the contributing guidelines correctly 👍🏼
