### ISSUE TITLE
Make debugging easier

### ISSUE THREAD

**Issue by ClasherKasten** [Mithil467/mitype#145]
**Is your feature request related to a problem? Please describe.**
I wanted to debug the application using the python debugger through `breakpoint()`.
But because mitype is made using `curses`, this isn't very easy or even unfeasible.

**Describe the solution you'd like**
There should be a better way to debug the application,
An idea for that would be to use [remote-pdb](https://pypi.org/project/remote-pdb/)
Sample scripts to ease the use of the tool could look like the following:
- `testing/debug-mitype`
```bash
#!/usr/bin/env bash
export \
    PYTHONBREAKPOINT=remote_pdb.set_trace \
    REMOTE_PDB_HOST=127.0.0.1 \
    REMOTE_PDB_PORT=4444 \
    REMOTE_PDB_QUIET=1
exec mitype "$@"
```
- `testing/debug-attach`
```bash
#!/usr/bin/env bash
exec rlwrap telnet 127.0.0.1 4444
```

**Additional context**
This code (and the idea) is not mine, instead it is taken from [babi](https://github.com/asottile/babi)

**Comment by Mithil467** [comment]
Hey @ClasherKasten 👋
Thanks for the issue.

To debug mitype, I use VS Code's [python debugging](https://code.visualstudio.com/docs/python/debugging) funcionality and it works pretty well. There might be other benefits your solution has to offer, but I would recommend not attaching any debugging scripts to the project, unless it becomes absolutely necessary. And it looks like running it on windows is going to be tricky.
Let me know if you need any help here.

**Comment by ClasherKasten** [comment]
Thanks for the response @Mithil467.
I think I don't need any more help on this and just gonna close the issue and corresponding PR, I feel like this is the right choice for now.
