### ISSUE TITLE
Show text ID at top left of window

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#15]
There is enough space to fit in the ID of the current text from database at top left.
![image](https://user-images.githubusercontent.com/41439841/93654470-39535b00-fa3b-11ea-99f6-0169a82ab74f.png)
This is a good feature as the user might like a particular text, but there is no way to retest on the same text.
With this feature user can get the ID and rerun `mitype -i ID`

**Comment by alphaxyz** [comment]
I'm working on it.
