### ISSUE TITLE
Incorrect handling of difficulty level 0

### ISSUE THREAD

**Issue by asd153866714** [Mithil467/mitype#151]
### Subject of the issue
The program does not handle the case when a difficulty level is 0. Instead of displaying an error message and exiting the program, it continues running.

### Your environment
* operating-system `WSL2 Ubuntu 20.04.06`
* version of Mitype `Mitype version 0.2.4`
* version of Python `Python 3.8.10`
* which terminal and it's version if applicable `GNU bash, version 5.0.17`

### Steps to reproduce
Run the command in terminal
```
mitype -d 0
```

### Expected behaviour
The program should print `Select a difficulty level in range [1,5]` and then exit.

### Actual behaviour
The program continues running without displaying any error message or exiting.

### Your proposed fix (if any)
Replace `elif opt.difficulty:` with `elif opt.difficulty is not None:` This ensure `elif` condition will not be evaluated as `False` when `opt.difficulty` is 0.

https://github.com/Mithil467/mitype/blob/692f9057e3d9cb49d0f2b6b55ed92f343327868b/mitype/commandline.py#L38-L42

**Comment by Mithil467** [comment]
Thanks for the issue! @asd153866714
