### ISSUE TITLE
Apostrophes not typing on Windows

### ISSUE THREAD

**Issue by DeflateAwning** [Mithil467/mitype#155]
### Subject of the issue
Apostrophes not typing on Windows, When one appears in the text, it is impossible to get past it. No symbol is typed/registered when it is pressed.

The key types fine in every other program and in the terminal without `mitype` active. Otherwise, `mitype` appears totally functional. 

### Your environment
* Windows 10
* Mitype version 0.2.4
* Tried/reproduced in Python 3.8.10, Python 3.11.4
* Tried/reproduced in ConEmu, Windows Terminal, Command Prompt

**Comment by DeflateAwning** [comment]
Also failing on Windows 11, Mitype version 0.2.4, Python 3.9.13, Windows Terminal

**Comment by DeflateAwning** [comment]
I'd say go ahead and fix it and then submit a PR

**Comment by Mithil467** [comment]
Thanks for reporting the issue! @DeflateAwning 

This is a bug with windows_curses (https://github.com/zephyrproject-rtos/windows-curses/issues/41) and looks like it was introduced after v2.3.0.

I'd be pinning windows-curses to this version with the next release of mitype.

**Comment by DeflateAwning** [comment]
Issue still exists in v0.2.4 (latest right now via `pip`). I guess the tag isn't released on pip yet.

**Comment by Mithil467** [comment]
I've only now realized that python 3.11 is not supported with windows-curses v2.3.0. So even though the latest version for mitype is now v0.2.5, it fails to install the dependency rightly.

We might need to implement a hacky fix within mitype while still using the latest windows-curses to continue supporting py3.11 and py3.12.
