### ISSUE TITLE
Show more stats at end of each test

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#16]
Currently we are only displaying the typing speed. We can add other attributes like `Accuracy` and `Time taken` nearby.

**Comment by gudeliauskaspam** [comment]
I have interest in doing this!

**Comment by Mithil467** [comment]
Hi @gudeliauskaspam :wave:
Thanks for your interest!

Currently we are displaying the following test at the end of the test:
```
 Your typing speed is  61.20  WPM

 Press  Enter  to see a replay! 
```
We can also display additional stats such as:
```
 Your typing speed is  61.20  WPM
 Time taken: 35 sec
 Accuracy: 92.3 %

 Press  Enter  to see a replay! 
```
Feel free to suggest different ways to do so, or different stats if you have them on your mind! 💚

**Comment by gudeliauskaspam** [comment]
I want to count how many times the user typed wrong, do you mind giving a tip of in which part of the code can I implement it?
I'm a beginner and I'm having a little trouble to understand some parts.
Thanks! :)

**Comment by Mithil467** [comment]
No problem @gudeliauskaspam :)

Firstly you might need a class property to keep track of mistyped characters' count. That property e.g. `mistyped_char_count` should go inside `class App()` declaration in `app.py`. The method to calculate the accuracy should go into `calculations.py`.

`check_word` method in `app.py` should give you some info about checking mistyped characters. 

Please feel free to ask further help or clarification if required 👍🏼

**Comment by Mithil467** [comment]
Hey @gudeliauskaspam :wave:
Havent heard from you in a while.
Just wanted to know whether you are still interested in working on this issue?

**Comment by gudeliauskaspam** [comment]
Hey! sorry for the lack of information, I'm still working on it, I was a little busy with college, next week I'll open the pull request.

**Comment by gudeliauskaspam** [comment]
Heyy @Mithil467,
 I have a question I would like to share.
When we type an incorrect character if we give backspace we can correct it, even if we have this option, do you think that the accuracy implementation still makes sense?

**Comment by Mithil467** [comment]
Yes it does! @gudeliauskaspam 

If user types any character, we increment `total_chars_typed` (ignoring keys like backspace).
If user types a wrong character, we increment `wrongly_typed_char_count`.

We would use this formula `Accuracy = (total_chars_typed - wrongly_typed_char_count) / total_chars_typed`.

So if user hits a wrong key, we immediately take a note of it. Now even if he corrects it, the accuracy has been recorded.

Does this clarify things? If not feel free to ask :)

**Comment by Mithil467** [comment]
@gudeliauskaspam #56 was opened a few days ago to add time taken stat. So let's try and get it merged if possible.

We still have other stats to implement like the accuracy stat which you may work on :)

**Comment by gudeliauskaspam** [comment]
Oh sorry, I will work on it as soon as possible!

**Comment by Mithil467** [comment]
Was just notifying you about it :)
No worries 👍🏼

**Comment by gudeliauskaspam** [comment]
Dooone! :)
