### ISSUE TITLE
App crashes when certain keys are pressed

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#17]
App crashes when certain keys are pressed.

### Steps to reproduce
Run mitype. Press any of these keys:
- Any key on numpad when numlock is off.
- Arrow keys
- fn + function keys

### Expected behaviour
These key presses should be ignored.

### Actual behaviour
Traceback:
```
  File "/home/mithil/p/mitype/mitype/app.py", line 84, in main
    self.typing_mode(win, key)
  File "/home/mithil/p/mitype/mitype/app.py", line 108, in typing_mode
    self.key_printer(win, key)
  File "/home/mithil/p/mitype/mitype/app.py", line 198, in key_printer
    self.appendkey(key)
  File "/home/mithil/p/mitype/mitype/app.py", line 239, in appendkey
    self.current_word += key
TypeError: can only concatenate str (not "int") to str

```

### Your proposed fix (if any)
Add functions to keycheck.py to check for such keys for their string value or integer value.

**Comment by DarthMuzammil** [comment]
Hey @Mithil467 loving this command line applet.
A first timer here in the Open Source Community and this issue looks like one i might be able to tackle. 
Can i have this one ?

**Comment by Mithil467** [comment]
Hi @DarthMuzammil 👋🏼

I am glad you are enjoying the project.
Thank you for your interest in contributing! :tada:

Yes please you may go ahead.
