### ISSUE TITLE
Pressing arrow keys should bring the next or previous text

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#18]
For example, if currently I am on text with `ID=450`.
Pressing right arrow key should load text with `ID=451`.
Similarly, now pressing the left arrow key twice should load text with `ID=449`.

**Comment by jldohmann** [comment]
Hi, I am enjoying playing around with this app! Would love to help out with this issue for Hacktoberfest.

Just for clarity, when you say next or previous text, do you mean the sample text snippets stored in the database? So the arrows should filter thru the database entries?

**Comment by Mithil467** [comment]
Hi @jldohmann 👋🏼
Thank you for your interest in contributing! :tada:
I am glad you are enjoying the project.

Yes you are correct. Pressing the left arrow key should load text from database with `ID=ID-1` and right arrow key should load text with `ID=ID+1`.

**Comment by Mithil467** [comment]
If the user has already started to attempt the test, that is, he has hit his first key already, then the attributes to the test must reset. Like `start_time`, `first_key_pressed`, etc.
Now I just realized that this is a different issue in itself and hence #20. I am sorry I should have thought about it earlier itself.
Are you okay with first resolving #20 ? That will make this issue simpler.

Or if you want to just work on particularly one of the issues, or both the issues, that's totally fine, please let me know!

**Comment by Mithil467** [comment]
Seems like @thomas901 is willing to take over the issue #20 !

If you are willing to, you may want to have a look at #17 ! As you will be detecting arrow key presses, this issue is very related.
I am very sorry for the conflict. 😅 

Would you like to work on #17 or just this issue, its totally your call!

**Comment by jldohmann** [comment]
> Would you like to work on #17 or just this issue, its totally your call!

No worries, I'm happy to work on both! :smile:

**Comment by Mithil467** [comment]
That is really great!

**Comment by Mithil467** [comment]
Hey @jldohmann! :wave:

#17 has been assigned to someone else. Sorry for all the confusion created. 😅 
You may just continue with this particular issue!

**Comment by jldohmann** [comment]
No problem!! :smile:

**Comment by Mithil467** [comment]
Hey @jldohmann :wave:
Not having heard from you for a while, I hope everything is well.

Please confirm if you are willing and available to work on this issue!

**Comment by jldohmann** [comment]
hey @Mithil467 thanks for checking in. 

I unexpectedly got busy with commission work during October, and am still swamped. I won't be able to work on this right now!

**Comment by mrbasel** [comment]
Hey @Mithil467 , can I work on this?

**Comment by Mithil467** [comment]
Sure! @mrbasel  👍🏼 
Make sure you follow the contributing guidelines.
