### ISSUE TITLE
Backspace key doesnt work as intended

### ISSUE THREAD

**Issue by kriticalflare** [Mithil467/mitype#2]
### Subject of the issue
The backspace key instead of deleting the previous character , it acts as invalid input.

### Your environment
* Windows 10
* Cloned @ 909183098e04b0a426f2dba22c25c27b68463185
* Python 3.8.0
* cmd prompt

### Steps to reproduce
Press the backspace key 

### Expected behaviour
Delete the previous character 

### Actual behaviour
It doesnt delete the previous character but rather acts as invalid input ( as it doesnt match any of the characters)

**Comment by Mithil467** [comment]
@kriticalflare Thanks for your concern and interest in the project. This is a critical bug and will be fixed in upcoming commits. :+1:

**Comment by Mithil467** [comment]
Okay, this is fixed in master. This will be added in next release but will take some time since I need to improve few other things before initiating the release process.
Thanks again! 😊
