### ISSUE TITLE
Press ESC key to reset test

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#20]
Pressing ESC key while the test has already started should reset the text. Note: Currently replay mode cannot detect ESC key. So this issue applied to test mode only and not replay mode.

**Comment by thomas901** [comment]
I am interested in contributing to this project. I would like to try fixing this issue.

For clarification, what exactly would the text being 'reset' look like?

**Comment by Mithil467** [comment]
Hi @thomas901 👋🏼
Thank you for your interest in contributing! 😄

If the test timer has not started yet, that is, the `start_time` value is still `0` and the `first_key_pressed` is still `False`, then pressing `ESC` key would exit the app.
Otherwise, during the test, pressing `ESC` would reset the test back to start. The cursor is brought to first position, the timer is set to 0, basically all the attributes are reset, but the text is still the same and the app is now waiting for the user to hit his first key.
