### ISSUE TITLE
Vertical shrinking of screen beyond a limit causes app to crash

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#23]
### Steps to reproduce
Start mitype. Reduce the size of the terminal vertically. It will crash after a certain point where screen becomes smaller than what is required to print the text.

### Expected behaviour
Mitype should:
1. Print to stdout a user friendly text message like "Window too small to print given text"
2. Exit

### Actual behaviour
Crashes with traceback -
```
  File "/home/mithil/p/mitype/mitype/app.py", line 354, in resize
    self.setup_print(win)
  File "/home/mithil/p/mitype/mitype/app.py", line 173, in setup_print
    win.addstr(2, 0, self.text, curses.A_BOLD)
_curses.error: addwstr() returned ERR
```

### Your proposed fix
We have implemented a size check in the `initialize` method in app.py already which warns the user that the terminal is smaller than the amount of lines required. We can use a similar check in `resize` method.

**Comment by gudeliauskaspam** [comment]
Hey! I have interest in doing this one too if it's okay :)
and I'm going to open a PR during Hacktoberfest!

**Comment by Mithil467** [comment]
Hi @gudeliauskaspam  👋🏼

Thank you for your interest in contributing! :tada:
Yes it if fine, you may go ahead with it during hacktoberfest as well.

**Comment by gudeliauskaspam** [comment]
hey @Mithil467 , sorry for the lack of news, I will start working on this problem next week :)

**Comment by gudeliauskaspam** [comment]
as far as i could understand the problem and the code in initialize method, a solution would be to count how many characters or maybe words fit in the box vertically

**Comment by Mithil467** [comment]
Have a look at this line, this is what is being done once at the start of the program.
https://github.com/Mithil467/mitype/blob/10792fcfe6d4591977fd235110fdddc054557429/mitype/app.py#L157
So at the start, we already are checking if window size if enough to print the text.

Similarly, we will need a check inside resize function.
https://github.com/Mithil467/mitype/blob/10792fcfe6d4591977fd235110fdddc054557429/mitype/app.py#L387

**Comment by gudeliauskaspam** [comment]
sorry I got it wrong, thanks for clarifying!

**Comment by gudeliauskaspam** [comment]
I fixed this problem and new ones appeared.
My solution, even if it is consistent in my point of view, behaves in such a way that the application closes without error whenever the resize is done.
I'm working on it, sorry for the long time.

**Comment by Mithil467** [comment]
No issues. Just make sure you are on the latest code on master before working!

**Comment by gudeliauskaspam** [comment]
hey, @Mithil467. I need your help.
I made this check

```python
        self.text_height = word_wrap(self.original_text_formatted, self.window_height)
        
        if self.window_height < len(self.text_height) + 3:
        	curses.endwin()
        	sys.stdout.write("Window too small to print given text")
        	sys.exit(1)
```

When I increase or decrease the size of the terminal, it says "Window too small to print given text".
this should not happen when increasing.
 it doesn't make sense for me not to work :sob:

**Comment by Mithil467** [comment]
The issue here is, you are comparing it with len(text) but that returns the length of the string and not the vertical height of the window required.

Currently there exists a check here -https://github.com/Mithil467/mitype/blob/d3f756ac28b707e2a18556bb993176af978f9151/mitype/app.py#L154

We have to do something similar in the resize function here -
https://github.com/Mithil467/mitype/blob/d3f756ac28b707e2a18556bb993176af978f9151/mitype/app.py#L409

**Comment by gudeliauskaspam** [comment]
Finally done :)

**Comment by Mithil467** [comment]
Thank you so much for the fix! @gudeliauskaspam 😄
