### ISSUE TITLE
Cursor position must be at beginning of text

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#26]
### Steps to reproduce
Start a new test. 

### Expected behaviour
Set the cursor position to start of text.
![image](https://user-images.githubusercontent.com/41439841/94357552-6d6ff100-00b7-11eb-8bc2-28e03fd41272.png)

### Actual behaviour
Tell us what happens instead
The cursor's default position is at the end of text.
![mitype cursor issue](https://user-images.githubusercontent.com/41439841/94357534-3d285280-00b7-11eb-90a4-ad40c2217d43.png)

**Comment by SanchitJain123** [comment]
Hey @Mithil467, I've used this application and I absolutely loved it. I would like to solve this issue.

**Comment by Mithil467** [comment]
Hey @SanchitJain123 :wave:

I am glad you are enjoying the project. We would love to have your contribution.

Please do check the contributing guidelines for further details. :)

**Comment by SanchitJain123** [comment]
@Mithil467 I have found the solution to the issue. If you don't mind, I will open PR during hacktoberfest :)

**Comment by Mithil467** [comment]
That's great :)
