### ISSUE TITLE
Display stats during replay

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#27]
Currently, you can see the stats only when the test or replay has finished.
![image](https://user-images.githubusercontent.com/41439841/94358569-b035c700-00bf-11eb-86b2-4b99d1581ffd.png)

But during the replay there is no way of knowing what the stats were.

When user hits enter to replay, we should display the stats at the bottom of the screen on the last line.

It feels like some other position like top right would have worked as well, but that is because we only have 1 stat currently.
But very soon we will be having a few more (see #16 ) , so last line seems feasible.

**Comment by RiturajJain** [comment]
Hi, I have played around with this app and would love to contribute to this project. Can I start working on this issue ?

Also, can I work on an issue that is already assigned to someone else ?

**Comment by Mithil467** [comment]
Hey @RiturajJain :wave:

Thank you for your interest in contributing to mitype! You can proceed with this for sure. 👍🏼 
Before starting please read the Contributing guidelines.

About working on issues assigned to someone else, I really appreciate your interest. But they have been assigned because they were willing to work on it and they commented so under the issue! Hence we would like to have others to contribute as well :)

**Comment by Mithil467** [comment]
Hey @RiturajJain :wave:
Havent heard from you in a while.
Just wanted to know if you are still interested in working on this issue?

**Comment by RiturajJain** [comment]
Hi @Mithil467,

Yes, I am. I will be making a PR soon.

**Comment by Mithil467** [comment]
>When user hits enter to replay, we should display the stats at the bottom of the screen on the last line.
@RiturajJain 

I need to be a bit clear with this statement. By this I mean the very bottom most line where the terminal ends.
Print it as:
`WPM:65`
