### ISSUE TITLE
Hide cursor when showing result

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#28]
After completing the test, we see the stats -
![image](https://user-images.githubusercontent.com/41439841/94455480-bebfd380-01d0-11eb-9975-9ba02c507720.png)

The cursor is placed at the end.

Let's hide the visibility of the cursor when displaying stats after test. But the cursor must be visible for the rest of the time.

Refer to the python curses documentation [here](https://docs.python.org/3/library/curses.html).

**Comment by jacobggman** [comment]
can I do that?

**Comment by Mithil467** [comment]
Hey @jacobggman 👋🏼 

Thanks for your interest in contributing to mitype! Yes you may work on this. Please read our contributing guidelines before getting started.

**Comment by mananchawla2005** [comment]
Hey @jacobggman Added a pull request related to this issue.

**Comment by Mithil467** [comment]
Hey @mananchawla2005 👋🏼 
I really appreciate your effort in contributing to mitype! However, since @jacobggman has requested to fix this earlier, I request to please let him take over the issue.

We'll wait for 6 days for @jacobggman to try solving this issue. Otherwise you may take over. Sounds cool?

Please understand the situation and try to comment on the issue beforehand! Cheers! 👍🏼

**Comment by mananchawla2005** [comment]
> Hey @mananchawla2005 👋🏼
> I really appreciate your effort in contributing to mitype! However, since @jacobggman has requested to fix this earlier, I request to please let him take over the issue.
> 
> We'll wait for 6 days for @jacobggman to try solving this issue. Otherwise you may take over. Sounds cool?
> 
> Please understand the situation and try to comment on the issue beforehand! Cheers! 👍🏼


Yup absolutely its more than fine. @jacobggman Actually i am a bit new in open source. Will try to contribute as much as possible!

**Comment by Mithil467** [comment]
Great to know you've found interest in contributing to open source with mitype!

Thanks for understanding @mananchawla2005  Meanwhile you may also want to keep an eye on the upcoming issues on the project! You can "watch" the repo (On top right, besides star).

That will notify you about new issues, if any :)

**Comment by mananchawla2005** [comment]
> Great to know you've found interest in contributing to open source with mitype!
> 
> Thanks for understanding @mananchawla2005 Meanwhile you may also want to keep an eye on the upcoming issues on the project! You can "watch" the repo (On top right, besides star).
> 
> That will notify you about new issues, if any :)

Yup did it thanks anyways!

**Comment by jacobggman** [comment]
Done. I will make PR in October because of Hacktoberfest
