### ISSUE TITLE
Suggest more features and ideas for implementing in mitype

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#30]
## Hey everyone :wave:

I am very happy to see all the love this project has been receiving! 💟

This thread is dedicated for discussions related to improvement of mitype and a place to share your ideas. 

We would love to have your sugestions, so feel free to comment them below 😄

**Comment by BassCoder2808** [comment]
We can add that if a user has a slow typing speed. Then we should suggest them some links or some suggestion to improve it.
The next thing we can do is to give topics according to categories. So basically first we will sort the text according to different categories and then when the user chooses a particular category we will show the texts/samples of that fields.

**Comment by BassCoder2808** [comment]
I had a doubt regarding the closure of this issue as this is a discussion forum how will you assign this to a particular person and what we have to do in the pull requests so that it gets accepted.
Can you please elaborate on it.

**Comment by Mithil467** [comment]
Hey @BassCoder2808 :wave:

I created this issue for discussion related to improvements and ideas. So there is nothing to work upon here (as in code) and hence no one will be assigned. If there is a good feature or issue, we will implement it going ahead.

I am glad you have a suggestion for the project. 😄 

However, the resources to improve speed can be easily googled for and technically, it is not increasing much value of the project.

Giving categories choosing option is great, but it doesn't have a high use case. Also, implementing it would be difficult as we would need to get texts of all sorts. Hence the option to choose your own custom text is available through `--file` command line parameter.

Thanks for your input!

**Comment by himadriganguly** [comment]
Realtime **WPM** on the top left corner of the screen. I think it will be a good feature. I am working on it will create a PR.

**Comment by Mithil467** [comment]
Hey @himadriganguly :wave:
Thanks for the suggestion!
It looks visually appealing. However, realtime stats are a major distraction. 
Hence I always refrained from implementing it.

**Comment by himadriganguly** [comment]
But it will be helpful for the user. It gives realtime feedback to the user. I implemented it but it doesn't look a distraction. But definitely, it's your decision to merge the PR or not.

**Comment by Mithil467** [comment]
Alright! 🙌🏼 
The realtime feedback sounds good @himadriganguly 

@ac030540 has some good points about this
- It will encourage them to type faster in the session to achieve their target.
- If we get results at the end then it's often hit or miss.

May you please raise a feature request issue for this? We will discuss it further there. 😄

**Comment by himadriganguly** [comment]
@Mithil467 raised feature request issue.

**Comment by himadriganguly** [comment]
Another idea is to rotate text using the **CTRL+R** key. It will be better to rotate the text as well if the user wants.

**Comment by Mithil467** [comment]
Rotate as in changing the text to next text? If that is what you mean then yep #18 is under process!

**Comment by himadriganguly** [comment]
> Rotate as in changing the text to next text? If that is what you mean then yep #18 is under process!

Ok great.

**Comment by bchmnn** [comment]
The database and the command line options could be extended to support code samples (e.g. from GitHub repos) ([inspiration](http://www.speedcoder.net/)).
For example `mitype -l python` gives you some random python code snippet.

**Comment by Mithil467** [comment]
Hey @bchmnn :wave:
Thanks for the suggestion! :)
All newlines and tabs and other combinations of whitespaces are squashed in the sample text. Enter key and tab key is reserved for some other purposes. 
Also, this will require usage of other keys, like arrow keys because most people tend to first write the brackets () then they press left arrow key, then enter further code, as in `void main(int argc, char** argv)`
So currently, there is no possibility of writing code, as it will bring in lot of complexity.

**Comment by SanchitJain123** [comment]
Hi @Mithil467, the idea is that we can create user-profiles, through which the user can track the history of their typing test that they have taken. A progressing history does increase morale as you aim for better speed. Also, we can let them add friends too to see how other people are doing in the typing tests.

**Comment by Mithil467** [comment]
Yes @SanchitJain123 awesome!
Isssue #39 has been created to address this! :)

**Comment by SanchitJain123** [comment]
Oh, maybe I was a bit late, what about adding friends as well.

**Comment by Mithil467** [comment]
Do you mean some web platform to have users on board, and then socializing? This would be entirely a new different project in itself. So currently I am not looking into that part of the project! :)

**Comment by Unviray** [comment]
Before implementing other features, why doesn't create an HUD. I mean a welcome page which we can choose to **start**, tweak **settings**, view **history** of score and **quit**

**Comment by NinoDoko** [comment]
I'm a big fan of typeracing, and I want to contribute! One suggestion I can make is a way to restart the game, so you don't have to run the command again. Where this would work in the end screen and in the middle of a text - sometimes you mess up big time. 

I already made this by having Tab be used as a restart button, but since you mentioned above that Tab is reserved, I can probably try and get a key-combination trick to work.

**Comment by Mithil467** [comment]
Awesome @Unviray Currently! It is very simple and straight forward to access all the features through command line parameters. Though I am still considering a configuration setting to be added, just that there aren't enough attributes to configure. If someone can find a way to specify any he value for color of text or background, etc (currently by default there are only about 8), it would be cool!

**Comment by Mithil467** [comment]
Very happy to see your enthusiasm for contributing to mitype! @NinoDoko 👋🏼 
Really glad to have suggestions from you :)

PR #33 has been initiated with the exact same use case. But there is also #18 which loads next or previous text from database. For any user, these text samples would be uniquely random! Hence it serves the same purpose. So instead I have asked the contributor to restart current text upon pressing `tab`. Hence I mentioned `tab` key is reserved!

**Comment by Jitsusama** [comment]
I've noticed some minor typos and docstring inconsistencies. Would that be an alright thing to open up a PR for?

**Comment by Jitsusama** [comment]
I was also noticing some aspects of this program that differs from other speed typers I've used, mainly how when you make a typo you have to backspace out your mistake. Would you welcome a PR to call this detail out in README.md/--help?

**Comment by Mithil467** [comment]
Hey @Jitsusama 👋🏼 
Very glad to see your interest in contributing to mitype :)

You may want to create an issue for docstring inconsistency and work on it :)

A PR for adding docstrings to all existing functions is highly appreciated. Along with this, you may slip in the typo fixes in same PR. But if there are just typos, I request you to create an issue instead. Let me know if you are interested to work on this!

Regarding the detail of erasing the mistype word, it is not required as the user will understand it on the first run itself, just a bit of trial :)

**Comment by Jitsusama** [comment]
I'll create an issue on it shortly, thanks.

**Comment by Mithil467** [comment]
Hey everyone! :wave:

Thank you very much for all your suggestions, ideas and PRs that has made mitype better. ❤️
I'm closing this thread, but you can always comment here or create an issue for a feature request :)
