### ISSUE TITLE
Show WPM in real-time 

### ISSUE THREAD

**Issue by himadriganguly** [Mithil467/mitype#32]
**Is your feature request related to a problem? Please describe.**
Not a problem but an enhancement to the application.

**Describe the solution you'd like**
It will show up on the top left corner of the screen and as the user types, it will update the value automatically in real-time.

**If it is not related to any problem**
It is not a problem but an enhancement to show realtime WPM speed to users.

**Additional context**
![mitype](https://user-images.githubusercontent.com/5839433/94655971-0c495700-031d-11eb-8d3e-f0ccb1c5585e.png)

**Comment by Mithil467** [comment]
Hi @himadriganguly :wave:
Thanks for the issue :)

Please read the contributing guidelines before starting.
You may go ahead with the fix!
