### ISSUE TITLE
Add ability to restart mitype without closing and re-calling it

### ISSUE THREAD

**Issue by MiConnell** [Mithil467/mitype#33]
It would be nice to be able to hit a key to restart the program instead of closing out and calling `mitype` after every run.

**Comment by Mithil467** [comment]
Hey @MiConnell ! :wave:

Thanks for raising this issue. This indeed is a nice addition, but #18 does a similar thing. As the immediate right or left text must be random for any user.

We can implement pressing tab to start test with current sample text again. Currently pressing esc currently during the test is happening, resets the test. Make sure we want to restart test if tab is pressed only when stats are showing.

**Comment by MiConnell** [comment]
Sorry if my naming didn't make it very clear, but all this enhancement request does is start a new random test instead of requiring the user to close out when they're done and re-type `mitype` to start a new test. The escape functionality to restart the current test seems to work just fine and I wouldn't want to change that.

I see #18 is already assigned so if you believe that will offer similar enough functionality I can wait for that to be implemented.

For reference, here's what PR #31 does:

After finishing the test, a new line will show with the option to press `TAB` to try a new test
<img width="591" alt="Finished" src="https://user-images.githubusercontent.com/14168559/94728557-444c9c00-0315-11eb-9aea-31b27ca7f77b.png">

Pressing tab just restarts the program with a random id
<img width="585" alt="Next" src="https://user-images.githubusercontent.com/14168559/94726570-46f9c200-0312-11eb-9d94-41c1479265b8.png">

**Comment by Mithil467** [comment]
Glad you explained it. Yep understood. I did run your branch locally and test it out earlier 😄 

Yes #18 serves similar purpose!

So instead what we could implement is:
- Pressing tab to start test with current sample text again. 
- Currently pressing esc currently during the test is happening, resets the test.
- Restart test if tab is pressed only when stats are showing.

Are you okay with this?
Please ask if you have any doubts regarding this :)

**Comment by Mithil467** [comment]
Hey @MiConnell :wave:
Your contribution is valued very much :)

Are you willing to still work on this issue according to the above requirements?

**Comment by MiConnell** [comment]
Sure thing, I'll plan on having something done early this week!

**Comment by MiConnell** [comment]
Hello, I've updated PR #31 for your review.
### Pressing tab to start test with current sample text again.
- Pressing escape before starting the test exits mitype. (existing feature) ✓
- Currently pressing esc currently during the test is happening, resets the test. (existing feature) ✓
- Restart test if tab is pressed only when stats are showing. (new feature) ✓
