### ISSUE TITLE
Emojis dont render

### ISSUE THREAD

**Issue by kriticalflare** [Mithil467/mitype#4]
### Subject of the issue
The keyboard and star struck emojis dont render properly

### Your environment
* operating-system - Windows 10 1903
* version of Mitype - cloned @ 8a51950
* version of Python - Python 3.8.0
* terminal - cmd

### Steps to reproduce
clone and run local_test.py

### Expected behaviour
The emojis to render

### Actual behaviour
Emojis dont render
<img  src="https://user-images.githubusercontent.com/42350771/77570947-8cb47880-6ef2-11ea-9b8c-8d8ebcde4926.png">

**Comment by Mithil467** [comment]
Can confirm this doesn't work on windows.
Seems like windows command prompt doesn't support UTF-8. And it of course wont be limited to windows cmd.

If it doesn't support emojis, the app needs to make sure that no garbage elements are printed. For which I need to find out whether the terminal itself supports emojis.

So I'll be trying to find a way to detect if the terminal supports emojis.

Thanks for the issue @kriticalflare !

**Comment by Mithil467** [comment]
I'm removing emojis for now, as I haven't really gotten a great lead with them.  I am considering to add it later once I have enough knowledge for sure.
