### ISSUE TITLE
Cannot exit mitype with CTRL+C on windows

### ISSUE THREAD

**Issue by diegoramosb** [Mithil467/mitype#43]
### Subject of the issue
The app is not quitting in test or replay mode using ctrl+c. It only quits in test mode pressing esc.

### Your environment
Windows 10
0.2.0
3.7.3
Windows cmd

### Steps to reproduce
1. Run the app
2. Press ctrl+c

Or 
1. Run the app
2. Finish a test
3. Press enter
4. Press ctrl+c

### Expected behaviour
The app should exit

### Actual behaviour
In test mode, "^C" appears in the lower area where the current word usually appears. On the other hand, nothing happens in replay mode. In fact, the app can only be closed by closing the cmd window from that point on.

### Your proposed fix (if any)
I believe the app is registering ctrl+c as a keystroke for the typing test and not as the usual "exit program" command. I would like to fix this for this year's Hacktoberfest.

**Comment by Mithil467** [comment]
Hey @diegoramosb ! 👋🏼 
Glad to have this issue! Yes can confirm this bug exists.

You may go ahead to solve this :)
Make sure you follow the contributing guidelines. 👍🏼

**Comment by ElijahAhianyo** [comment]
Hi, @diegoramosb @Mithil467  has anyone taken this up? i'd love to work on this

**Comment by Mithil467** [comment]
Hey @ElijahAhianyo :wave:
Thanks for your interest in contributing. This issue has been assigned to @diegoramosb.

Please confirm, are you still willing to work on this @diegoramosb? :)

**Comment by Mithil467** [comment]
There's an update to this issue, can exit mitype with ESC key now! :)

**Comment by diegoramosb** [comment]
Hi @Mithil467 I am working on it. I just saw the update and will make the pull request in a bit.

**Comment by Mithil467** [comment]
This issue has also been raised on [windows_curses](https://github.com/zephyrproject-rtos/windows-curses/issues/8). Just something to keep track of.
