### ISSUE TITLE
Add support for Chinese chars

### ISSUE THREAD

**Issue by zronghui** [Mithil467/mitype#44]
1. Support Chinese
2. Ignore the comment. The comment start identifier (such as #) can be specified by the user or determined by the file suffix name
3. Ignore multiple spaces  and merge multiple Spaces into one. or just ignore tailing blank spaces

**Comment by Mithil467** [comment]
Hey @zronghui 👋🏼 
1. I believe that chinese must be already supported, you may try with a text file of your choice and let me know.
2. I feel there is no need to implement comments as such for now, as you may just edit the text file for your needs.
3. Yep this is implemented already!

**Comment by Mithil467** [comment]
Tested localy. Does support chinese chars already! :)
