### ISSUE TITLE
Taking care of Dependencies that are OS dependent

### ISSUE THREAD

**Issue by jai-dewani** [Mithil467/mitype#45]
**Is your feature request related to a problem? Please describe.**
It's a one-step simple problem that is people need to install two pip packages separately to run mitype on windows

**Describe the solution you'd like**
There are a lot of examples of how to deal with dependencies that are OS-dependent. Check out some on [stackoverflow](https://stackoverflow.com/questions/16011379/operating-system-specific-requirements-with-pip), another [stackoverflow](https://stackoverflow.com/questions/58927064/pip-package-with-os-specififc-dependency) and the docs on [PEP 508](https://www.python.org/dev/peps/pep-0508/#environment-markers)

**If it is not related to any problem**
It's more of a convenience thing more than a problem

**Comment by Mithil467** [comment]
Hi @jai-dewani 👋🏼 

This is an interesting feature indeed. Do you want to give it a try?

**Comment by jai-dewani** [comment]
Sure, I will love to give it a try!

**Comment by Mithil467** [comment]
Great! Get started by reading the contributing document :)

**Comment by jai-dewani** [comment]
One question though, I haven't checked the codebase but there seem to be no requirements in the setup.py so does this project actually requires nothing other than `windows_curses` in windows for this to run?

**Comment by Mithil467** [comment]
Yes that is right :)

Everything is provided by python standard library.
