### ISSUE TITLE
Stenography with Plover will not work with mitype

### ISSUE THREAD

**Issue by cominixo** [Mithil467/mitype#48]
### Subject of the issue
While using mitype with Plover for stenography, Plover will add a space before each word you type, which makes mitype say the word is invalid.

### Your environment
* Arch Linux 5.8.12-arch1-1
* mitype 0.2.0
* Python 3.8.5
* kitty 0.18.3

### Steps to reproduce
Install Plover and try to do a typing test in mitype with it enabled.

### Expected behaviour
Mitype should accept the input as valid.

### Actual behaviour
Mitype says the word is invalid.

### Your proposed fix (if any)
#47

**Comment by Mithil467** [comment]
I'm having trouble wrapping my head around this concept. Like its just a technique to allow typing right. So it shouldn't matter how the content is layed out, it should still enter the text in same order.

Does plover always add a whitespace to all words? Then in that case how is it possible to be used in real life typing?

**Comment by cominixo** [comment]
Stenography uses "chords", so basically you'll press a bunch of keys at once and it'll write the word, and then automatically put a space before it.

**Comment by Mithil467** [comment]
Yep I get it. But then I cannot use it daily life to type right? 🤔

**Comment by cominixo** [comment]
Why not? It's perfectly usable

**Comment by Mithil467** [comment]
Oh! But then what issue does one face when typing on mitype?

**Comment by cominixo** [comment]
The only problem is it will add the space before a word, and mitype will see it as invalid, especially when you get a word wrong, delete and rewrite it, because the cursor will be after the space, and then plover will add another space after that space.

**Comment by Mithil467** [comment]
Consider a sample text : "Some sample string"
So there's a limitation with Plover that it will be able to type : " Some sample string" with a space at beginning and not the original text?

**Comment by cominixo** [comment]
You can make it write "Some sample string" on the first stroke, there's a setting for that. I think the major problem is when erasing a word it will move the cursor after the last space, so you would start at "Some " and then you would write "sample" again and it would become "Some  sample".

**Comment by Mithil467** [comment]
Now I understand! Thanks :)
