### ISSUE TITLE
Typing window doesnt adapt to resizing cmd window

### ISSUE THREAD

**Issue by kriticalflare** [Mithil467/mitype#5]
### Subject of the issue
Typing window doesnt adapt to resizing cmd window

### Your environment
* operating-system - Windows 10 1903
* version of Mitype - cloned @ 8a51950
* version of Python - Python 3.8.0
* terminal - cmd

### Steps to reproduce
clone the repo.
Open cmd , it should open unminimized by default
Run local_test.py
Maximize cmd window

### Expected behaviour
The typing window to resize to properly utilize the full width of cmd screen

### Actual behaviour
The typing window doesnt adapt to the change in cmd window size.
![image](https://user-images.githubusercontent.com/42350771/77579368-351d0980-6f00-11ea-829b-5ba41a32ba2c.png)

**Comment by Mithil467** [comment]
Thanks for the issue @kriticalflare !
I have uploaded a fix in the latest commit.

Please let me know if the issue persists. Also, resizing terminal window is a work in progress. It does fulfill the needs of the issue and also of  #6 , but it is not a complete fix yet.

Resizing still doesn't work as intended after you type certain amount of characters. So my suggestion would be to not resize once you have started typing, or even better once the session itself has started.

Thanks for your efforts for testing mitype and filing issues !
Mitype needs a lot of improvement and thanks for being along 👍
