### ISSUE TITLE
New languages support

### ISSUE THREAD

**Issue by LucaPalumbo** [Mithil467/mitype#50]
Hi, I think it would be nice if mitype could also support other languages like Italian, French, Spanish and so on.

**Solution i'd go with**
Add other tables to database. Something like `data_it`, `data_es`, `data_fr`... with the same columns as data
Add a commandline feature ```-l``` or ```--lang``` that let you specify which language you want to write in.
Add a function in _database.py_ that select the text given the id from a given table. 
Add a ```function load_based_on_language``` to _commandline.py_

I'd like to work on this. I can also populate the italian db with some phrase.

**Comment by Mithil467** [comment]
Hey @LucaPalumbo :wave:

Mitype currently supports loading sample text from text files. Adding text phrases for various languages might be an overkill as there are many languages! That would also increase the package size significantly! Considering these points I'll close this issue.

However, very glad to know your interest in contributing to mitype! :)
