### ISSUE TITLE
Fix Sphinx documentation

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#53]
Since mitype is seeing some docstring improvements (#52), it would be a good time to also work on the sphinx documentation.

Currently the Sphinx setup lies in [docs](https://github.com/Mithil467/mitype/tree/master/docs) folder.

There were several changes to the project like moving from `README.rst` to `README.md` and the setup is very outdated.

**Comment by Jitsusama** [comment]
Sounds great! Just to make sure the expectations are clear, is this your hopes:

1. Make sure current Sphinx configuration is "up to snuff".
2. Make sure all source code modules are included in the Sphinx auto-generated documentation.
3. Copy most of the contents of README.md into the docs folder, but make it more appropriate as a general documentation page.

**Comment by Mithil467** [comment]
That sounds perfect @Jitsusama ! 🙌🏼
