### ISSUE TITLE
Pin the red color on the mispelled letter

### ISSUE THREAD

**Issue by AltheusV** [Mithil467/mitype#54]
Pin the red color on the mispelled letter

**Steps to reproduce**

* If the user misspelled a word, the red color will be pinned exactly on the first misspelled letter

**Expected behaviour**

![image](https://user-images.githubusercontent.com/30200769/95030431-10aba200-0686-11eb-836f-d22f76b8186c.png)

**Actual behaviour**

![image](https://user-images.githubusercontent.com/30200769/95030411-efe34c80-0685-11eb-8189-429dc60e110b.png)

**Your proposed fix (if any)**

I would like to work on this enhancement, if possible. I believe that it is a good enhancement because the actual behaviour for new users can be quite confusing. At first I did not understand that I mispelled a word and I continued to type.

Also, I am having some troubles to run the code locally. My changes does not have any effect on the application. I read the build.md file, can you explain with more details how to run in development mode?

**Comment by Mithil467** [comment]
Hey @AltheusV 👋🏼 

Currently series of character is highlighted hence stressing more on the fact that something is wrong, as compared to one highlighted character which might be visually missed. Also, confusion will exist for the first time until user does some trial and error, and is bound to happen even with this change! Hence I'll close this issue.

Other than that, I am very happy to know about your interest in contributing to the project! 🙌🏼 

To run in development mode, you gotta be in root folder of this repo, and run `python -m mitpye`. That should run mitype directly from local repo reflecting your changes. However if that fails, it might be running the globally installed version from pypi.

In that case you can use a virtual environment or uninstall global mitype to avoid conflict.
