### ISSUE TITLE
Visual glitch when using backspace to clear text on multiple rows

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#59]
### Steps to reproduce:
Start mitype, preferably with a relatively lesser width terminal window.
Spam any wrong keys so that the text overflows to next line as shown below.
![image](https://user-images.githubusercontent.com/41439841/96334494-d8955d80-108e-11eb-9171-60a684d8f967.png)
Try to clear those keys by pressing backspace.
![image](https://user-images.githubusercontent.com/41439841/96334502-e945d380-108e-11eb-9fbe-9db17ff6a6d7.png)

### Expected behaviour
Backspace should clear all the keys consistently.

### Actual behaviour
The logic works as expected and does indeed clear text but doesn't update the screen visually for the lines below, but works fine for top line.

### Proposed fix
Maybe we need to clear the entire screen if that is feasible.

**Comment by sks147** [comment]
Hi @Mithil467, can I pick up this issue.

**Comment by Mithil467** [comment]
Hey @sks147 :wave:
Thank you for your interest in contributing!
Please make sure to read the [contributing](https://github.com/Mithil467/mitype/blob/master/CONTRIBUTING.md) guidelines before getting started :)

**Comment by sks147** [comment]
Sure.

**Comment by jai-dewani** [comment]
Since it has been a long time and no update seems to happen, Can I work on this issue?

**Comment by sks147** [comment]
Hi @jai-dewani, you can pick up this issue. @Mithil467 really sorry for no updates on this. I got really busy.
Thanks again @jai-dewani, you can get this assigned to you.

**Comment by Mithil467** [comment]
@sks147 That's totally fine :)
@jai-dewani Sure you may go ahead with this!
You may refer to the PR #62 and just have a look at what was implemented and what conversation we had,

**Comment by jai-dewani** [comment]
Okay, restricting `current_word` seems like a very reasonable solution without over engineering this problem. A limit in the range of 20-30 sounds reasonable. 

Do you think we should inform the user in some way about him reaching the limit of the wrong letters he has typed? Maybe a sound  or a textual message at the bottom left/right saying   
`you have pressed too many wrong keys,  try backspace to go back and type correctly`

**Comment by Mithil467** [comment]
I like the idea of a visual indicator. We can change the color of the printed word to red (as we do when the user types incorrectly) when the max length is reached.

**Comment by jai-dewani** [comment]
Wow, that seems like an even better indicator, I'll get going then. 

I'll create a separate variable for the limit on `current_word` which can be easily updated to change the limit in the future if needed. Sounds good?

**Comment by Mithil467** [comment]
Yes. That'd be great :)
