### ISSUE TITLE
Erase typed word with CTRL+backspace

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#63]
Sometimes user might not realize he's typing incorrectly and continue typing multiple words. In such a scenario, one may prefer erasing the entire word with the help of the `ctrl + backspace` combo.

For example -
Current string is "quqick brown"
![image](https://user-images.githubusercontent.com/41439841/96744405-a2cfdc00-13e2-11eb-890c-70ef98f1e07e.png)

Pressing the key combo should erase the latest word -
Current string becomes "quqick "
![image](https://user-images.githubusercontent.com/41439841/96744498-bb3ff680-13e2-11eb-960d-25a0b400f915.png)

And hitting a second time should erase the other word too
Current string becomes ""
![image](https://user-images.githubusercontent.com/41439841/96744666-e9bdd180-13e2-11eb-9422-974218b320c4.png)

**Comment by mprovenc** [comment]
I would like to work on this

**Comment by Mithil467** [comment]
Hey @mprovenc 👋🏼 
Glad to know your interest. Make sure you read the [contributing guidelines](https://github.com/Mithil467/mitype/blob/master/CONTRIBUTING.md) before starting!

**Comment by Mithil467** [comment]
Hey @mprovenc 👋

Please confirm if you are willing and available to work on this issue!

**Comment by mprovenc** [comment]
I am still willing to work on this issue, have just been bogged down with some other work lately. It will probably be another week or so before I can start work on it again. If you need to reassign because of time, you can go ahead

**Comment by abstanton** [comment]
Hi, want me to work on this? Have used python and curses before, seems like it's not currently being worked on

**Comment by Mithil467** [comment]
Hi @abstanton 👋🏼 
Glad to know about your interest in contributing! You may work on this.
Please go through the contributing guidelines before starting.

**Comment by abstanton** [comment]
It appears to be tricky to detect a ctrl+backspace key combination curses. On my ubuntu machine ctrl+backspace in the terminal is bound to ^H (ctrl+h). However this may not be the same for all operating systems. There is no standard way to get this combination, any recommendations?

**Comment by Mithil467** [comment]
Keys do vary a lot with operating systems, the way we handle this is to check for those keys across all operating systems with both python 2 and 3. You rightly said, there's no standard way to get the key press.
Will have to experiment a bit in order to get the key combinations.
Check https://github.com/Mithil467/mitype/blob/a685c42f1f9a3733a2ae0a20084d4d8b40fd08e6/mitype/app.py#L495 and [keycheck.py](https://github.com/Mithil467/mitype/blob/master/mitype/keycheck.py) for understanding how certain keys are being detected currently.

You can implement for Ubuntu and open a PR, as you say it appears to be "^H". We will improvise it for different operating systems (with both py2 and py3) after that.

**Comment by mprovenc** [comment]
Hey @abstanton and @Mithil467, I had started working on this issue earlier in the semester, but things got very busy with school and I never ended up picking it up again. I was working on a Windows machine and found that this method seemed to work for detecting ctrl+backspace:
```
def is_ctrl_backspace(key):
    """Detects Ctrl+BACKSPACE key combination.

    This is used to delete back to previous wordbreak.

    Args:
        key (string):

    Returns:
        bool: Returns true if Ctrl+BACKSPACE is pressed.
            Returns false otherwise.
    """
    return key == "\x7f"
```
I believe that `\x7f` is ASCII DEL. Hope this helps.

**Comment by Mithil467** [comment]
This indeed is helpful.
Upon testing, I got the ascii value as `127` which is `7f` in hex.
Thank you very much for sharing your findings and contributing @mprovenc!
School is very demanding especially during the end of semester.

**Comment by jai-dewani** [comment]
Hey, @Mithil467 @mprovenc @abstanton is anyone still working on this?

**Comment by abstanton** [comment]
Hi @jai-dewani , I am still on this! Just been having a break due to hristmas + an operation but can start it again this week

**Comment by jai-dewani** [comment]
Cool!   
Just a tip, I was working on this issue on my windows machine, and the code for CTRL + backspace is `\x17` which is different from what @mprovenc found, so make sure to test both :) 
Best of Luck 👍

**Comment by Mithil467** [comment]
Thanks for your interest to work on the issue and for providing the information! @jai-dewani 
Alright, sure! 👍🏼 @abstanton

**Comment by jai-dewani** [comment]
Hey @Mithil467 are you working on this issue otherwise can you assign it to me?

**Comment by Mithil467** [comment]
Sure! :)

**Comment by jai-dewani** [comment]
Okay, my PR isn't working for all terminals. 
It's only working for VSCode terminal because they have a special mapping for `Ctrl+Backspace` as `^W`

If Interested in understanding how much of a mess terminal key mappings are, You can read about it here=> https://github.com/microsoft/terminal/issues/755

I can't come up with a clean solution right now, give me some more time, or maybe you can throw in some ideas on how should we move forward with this

**Comment by Mithil467** [comment]
Firstly, thanks for the PR!

You are correct about the mappings being very messy consdering which there might not even be a clean solution.
It seems difficult to get it working with linux but it seems to be possible with windows because in Cmd and Powershell, `Ctrl+Backspace` erases the entire word which means there might be a way to detect it.

Let's try to target windows only with this issue. If that also doesn't work, we will close it.

**Comment by Mithil467** [comment]
Let's merge #79. We can just have it working for at least a few terminals out there that have the key binding. Later we can try adding support for other terminals.
