### ISSUE TITLE
Share Score on Twitter

### ISSUE THREAD

**Issue by jai-dewani** [Mithil467/mitype#72]
**Is your feature request related to a problem? Please describe.**
It's not much of a problem but a way to bring more traction to this project, you must have seen websites where you can do some things and share your results on social media which brings more people into the project from there following and so on.....

**Describe the solution you'd like**
When the user completes the test we can provide a key combination which will open Twitter with pre-typed results like number of words, time taken, Words per minute, and a tag to your Twitter handle as a creator or you can create a Twitter handle of this project itself :p 

**If it is not related to any problem**
I already did :) 

**Additional context**
Not sure about this, but if there is any way to capture the window the user typed into and use this captured image in the tweet will be more awesome and no one can tampure with that kind of result compared to some pre-typed text

**Comment by Mithil467** [comment]
Thanks for the issue and the detailed description! @jai-dewani
Very interesting feature indeed. 🙌🏼 

Would you like to work on it?

**Comment by jai-dewani** [comment]
Sure, I came for some different issue but might as well contribute something :p 
What key combination do you think we can use for this? 
- CTRL + T (T for Twitter, wait isn't this shortcut for opening a new terminal on ubuntu?)
- CTRL + S (S for share) 
- Or you have some different key in your mind?

**Comment by Mithil467** [comment]
Great!
Yes, `CTRL+T` is used for opening a new tab on some terminals, especially on Ubuntu.
`CTRL+S` sounds good.

**Comment by Mithil467** [comment]
Capturing a screenshot of the terminal sounds awesome, but might be difficult to implement as a cross-platform feature.
Let's start with a simple text tweet. Later we can extend it to images.

We can think over the image part later.
Feel free to propose any other ways this could work out.

**Comment by jai-dewani** [comment]
Cool, I will go with `CTRL+S`.  

I'll work on just the text option as of now and will look for different ways capturing terminal screenshot can be done

**Comment by jai-dewani** [comment]
I am going though some ideas on what could be the content of the tweet? I have created [this][#1] link, try opening it. 
We also have to add a link which can guide the user to the project, I am confused between the the [docs](https://mithil467.github.io/mitype/installation.html) and the [pypi manager](https://pypi.org/project/mitype/) or maybe the github link of this repo.  

What are your views on this? 

[#1]: https://twitter.com/intent/tweet?text=Checkout%20this%20cool%20project%20by%20%40twiiter_id%20%0Amitype%3A%20a%20typing%20speed%20test%20in%20terminal%20where%20I%20scored%20an%20average%20of%20%2B%20wordmperminute%20%2B%20WPM%20

**Comment by Mithil467** [comment]
I see. We can tweet a simple message like [this]https://twitter.com/intent/tweet?text=My+typing+speed+is+65+WPM%21+Know+yours+on+mitype.%0D%0Ahttps%3A%2F%2Fpypi.org%2Fproject%2Fmitype%2F%0D%0A%23TypingTest+). It includes the link to the PyPi managerrepo, and hence also makes a small pop-up appear.

**Comment by jai-dewani** [comment]
Do you wanna add `Know yours on mitype created by @twiiter_useranme` for personal promotion?   
Just asking because I would have but different people have different opinions. 
Other than this, almost everything else is done. The program at the end looks like this 


![image](https://user-images.githubusercontent.com/33520257/103528498-134aad00-4eaa-11eb-9d2f-e1dace3fb6a8.png)

**Comment by Mithil467** [comment]
I agree with that. Let's go with [this ](https://twitter.com/intent/tweet?text=My+typing+speed+is+65+WPM%21+Know+yours+on+mitype.%0D%0Ahttps%3A%2F%2Fpypi.org%2Fproject%2Fmitype%2F+by+%40MithilPoojary%0D%0A%23TypingTest) then.

The `CTRL+S to share your result on Twitter` might overflow through the window if the width is less. Just `CTRL+S to share result` is better.

Good work! 🙌🏼
