### ISSUE TITLE
zsh: permission denied: mitype

### ISSUE THREAD

**Issue by LastCleanShirt** [Mithil467/mitype#75]
I just installed oh-my-zsh to my zsh and i reinstall mitype but when i run `mitype` on my iTerm2 it says zsh: permission denied: mitype

I already re-install and un-install mitype but it still doesn't work

**Comment by Mithil467** [comment]
Hi @LastCleanShirt 
Look at this solution [here](https://github.com/ohmyzsh/ohmyzsh/issues/849#issuecomment-8685169) and let me know if it helps.
