### ISSUE TITLE
Add support for german chars

### ISSUE THREAD

**Issue by IJustDev** [Mithil467/mitype#8]
### Subject of the issue
Unfortunately if I try to take the test with a German text with the `-f` flag I am not able to input characters needed for some words (like ä, ö, ü).

### Your environment
* OS: Debian 10
* MiType: 0.1.3
* Python 3.7.3

### Steps to reproduce
Grab yourself a German text like this:
```
Zu meiner Familie gehören vier Personen. Die Mutter bin ich und dann gehört natürlich mein Mann dazu. Wir haben zwei Kinder, einen Sohn, der sechs Jahre alt ist und eine dreijährige Tochter.
```
Save it to an file and run 
`$ python3 -m mitype -f <file-name>`
And try to get pass the `gehören` word.

### Expected behaviour
We should expect Mitype to handle special characters.

### Actual behaviour
Sadly you can not press the special char keys, they will just be ignored.

**Comment by Mithil467** [comment]
I am not much aware about the language but I would be happy to add German Support. Thanks for the issue, I appreciate that you have given a sample to work upon. Just let me know are there any more characters than these => yowäöüß€ÄÖÜẞ

**Comment by IJustDev** [comment]
For German there are only following characters:
`äöüÄÜÖß`.

Thank you very much!

**Comment by Mithil467** [comment]
Hi @IJustDev, I was able to add support for German characters on python 3 with commit https://github.com/Mithil467/mitype/commit/52fc0616c9416faca83d7154dd3ab8752eb860ee.
It will be great if you can clone Mitype and run the App locally. This change upon confirmation then can be published in the next version of Mitype.

@ac030540 I had to change the way other keys are detected as well, which might interfere with regular keys like backspace and escape keys on a mac. Please test it out.

**Comment by IJustDev** [comment]
Thank you very much! In the commit you've mentioned everything works fine!
