### ISSUE TITLE
Highlight errors on the end screen

### ISSUE THREAD

**Issue by CorentinGaillard** [Mithil467/mitype#81]
I'd love to be able to visualize the error I made during the run, as in the screenshot. 

![image](https://user-images.githubusercontent.com/44948182/122568509-185f7b00-d04a-11eb-802d-fe2b3fff0266.png)

Also, the same app ([*here*](http://dactylotest.free.fr//dactylotest/)) displays a "fluidity" score, which is higher the more stable you are while typing.
I believe it can be calculated from something like the variance of the time interval between two keystrokes.

**Comment by Mithil467** [comment]
The way mitype works is that you can't proceed to next word without correcting the previous one. So having this kind of visualization at the end of the run isn't really applicable.

We will look into fluidity score. That will be worked on under a separate issue :)

Thanks for the suggestion!

**Comment by CorentinGaillard** [comment]
I'll try to get a working example of what I mean for the highligting, I'm pretty sure it's relevant.
Thanks for the fluidity score :)

**Comment by CorentinGaillard** [comment]
Ok, I've got something working, but it's on a machine without internet, so I can't really commit.
There are just a few pieces of code added though, so I'm gonna put them here. I you wan't to, I probably can find a way to commit, but it's much easier for me to list here what I changed. 
all the changes are in the file app.py
in `__init__(self)`: 
```python
self.erased_keys = []
```
in `erase_key(self)`: 
```python
self.erased_keys.append(first_index_at_which_string_differ(self.current_string, self.text))
```
and lastly, in `update_state(self, win)` : 
```python
...
if index == len(self.text):  # already there
    for idx in set(self.erased_keys):
        win.addstr(
            2 + idx // self.window_width,
            idx % self.windows_width,
            self.text[idx]
            curses.color_pair(2),
        )
    ...
```
It results in the mistyped char being red, as in the screenshot below
![mitype](https://user-images.githubusercontent.com/44948182/123105378-0c9ffa00-d438-11eb-81dc-8f7872973720.png)

I have not tested this change anywhere else than on my machine, but I belive that it's simple enough so it won't break anything.

**Comment by Mithil467** [comment]
Hey @CorentinGaillard :wave:
I'm splitting this issue as it is a combination of 2 issues right now.

Can you help me understand the fluidity score?
If it is the variance of the time interval between two keystrokes, it might not make complete sense to the user. A more user-friendly stat could be the average time interval between two keystrokes.

**Comment by Mithil467** [comment]
I am closing this issue for now due to lack of information. Please feel free to open a new issue if needed!
