### ISSUE TITLE
Incorrect formatting on docstrings with multi-line return

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#84]
The formatting is messed up for the `return` section with multi-line description.
For example https://mithil467.github.io/mitype/api.html#mitype.keycheck.is_escape.

### Expected behaviour
Formatting should be the same for all lines.

### Actual behaviour
![Screenshot 2021-09-01 173923](https://user-images.githubusercontent.com/41439841/131669110-af58d31e-2e58-45d9-9e2c-cc9df5e84676.png)

### Your proposed fix
With reference to the solution mentioned in issue https://github.com/sphinx-contrib/napoleon/issues/4, all the docstrings with multi-line return section need to be indented accordingly as -
```
    Returns:
        bool: Returns `True` if pressed key is ESC key.
        Returns `False` otherwise.
```

**Comment by 31Sanskrati** [comment]
I want to solve this issue, Can I?

**Comment by Mithil467** [comment]
Hey @31Sanskrati 👋🏼 
Thank you for your interest in contributing!
Please make sure to read the [contributing guidelines](https://github.com/Mithil467/mitype/blob/master/CONTRIBUTING.md) before getting started :)
