### ISSUE TITLE
Ending support for Python 2

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#87]
<div type='discussions-op-text'>

<sup>Originally posted by **Mithil467** September  3, 2021</sup>
Python 2 support was added initially because it was really easy to do so. But it is not really necessary. The advantages are minimal, and the development overhead is far greater with testing code on both Python versions and ensuring that code is compatible with Python 2.

So moving on, all the code supporting Python 2 will be removed and further features will be developed by keeping Python 3 in mind.

Any contributions towards achieving this is really appreciated! 😄</div>

These are some of the changes required to achieve this -
- [x] Remove any version checks and code supporting Python 2
- [x] Remove `__future__` imports
- [x] Remove Python 2 classifier from setup.py
- [x] Update any comments or docstrings written for Python 2
- [x] Update README

**Comment by adityakk29** [comment]
I'm working on tasks 1, 2 and 4.
